import "server-only";

export const INTENTS = [
  "TOP_WINNERS_QUERIES",
  "TOP_LOSERS_QUERIES",
  "TOP_WINNERS_PAGES",
  "TOP_LOSERS_PAGES",
  "HIGH_IMPRESS_LOW_CTR_PAGES",
  "POSITION_UP_CLICKS_DOWN_QUERIES",
  "CTR_OPPORTUNITIES_QUERIES",
  "BRAND_VS_NONBRAND",
  "CANNIBALIZATION_QUERIES",
  "DRILLDOWN_PAGE_TO_QUERIES",
] as const;

export type Intent = (typeof INTENTS)[number];

